language: r
sudo: required


apt_packages:
  - libsuitesparse-metis-3.1.0

install:
  - wget https://github.com/kaskr/adcomp/archive/master.zip
  - unzip master.zip
  - cd adcomp-master && make install-metis
