language: r
sudo: required

install:
  - apt-get install libsuitesparse-metis-3.1.0
  - wget https://github.com/kaskr/adcomp/archive/master.zip
  - unzip master.zip
  - cd adcomp-master && make install
