language: r

sudo: required

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

env:
  global:
    - OS=$(uname -s)

matrix:
  exclude:
  - r: devel
    os: osx


install:
  - R -e 'install.packages(c("TMB","roxygen2","devtools"),dependencies = c("Depends", "Imports", "LinkingTo", "Enhances"))'
  - make install_dependencies 

script:
  - make check

after_success:
  - cat argosTrack.Rcheck/00check.log
  - cat argosTrack.Rcheck/00install.out

after_failure:
  - cat argosTrack.Rcheck/00check.log
  - cat argosTrack.Rcheck/00install.out
