language: r

sudo: required
cache: packages

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

env:
  global:
    - OS=$(uname -s)

r_check_args: --as-cran

r_packages:
  - RcppEigen
  - TMB
  - Matrix
  - knitr
  - rmarkdown

after_failure:
  - if [ ${OS} = Darwin ]; then cat /Users/travis/build/calbertsen/argosTrack/argosTrack.Rcheck/00check.log; fi
  - if [ ${OS} = Darwin ]; then cat /Users/travis/build/calbertsen/argosTrack/argosTrack.Rcheck/00install.out; fi
  - if [ ${OS} != Darwin ]; then cat /home/travis/build/calbertsen/argosTrack/argosTrack.Rcheck/00check.log; fi
  - if [ ${OS} != Darwin ]; then cat /home/travis/build/calbertsen/argosTrack/argosTrack.Rcheck/00install.out; fi
  - ./travis-tool.sh dump_logs

after_success:
  - if [ ${OS} = Darwin ]; then cat /Users/travis/build/calbertsen/argosTrack/argosTrack.Rcheck/00check.log; fi
  - if [ ${OS} = Darwin ]; then cat /Users/travis/build/calbertsen/argosTrack/argosTrack.Rcheck/00install.out; fi
  - if [ ${OS} != Darwin ]; then cat /home/travis/build/calbertsen/argosTrack/argosTrack.Rcheck/00check.log; fi
  - if [ ${OS} != Darwin ]; then cat /home/travis/build/calbertsen/argosTrack/argosTrack.Rcheck/00install.out; fi
