language: r

sudo: required

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

env:
  global:
    - OS=$(uname -s)


install:
  - R -e 'install.packages(c("roxygen2"),dependencies = c("Depends", "Imports", "LinkingTo", "Enhances"))'
  - make install_dependencies 

script:
  - make check
  - make testquick

after_success:
  - cat argosTrack.Rcheck/00check.log
  - cat argosTrack.Rcheck/00install.out

after_failure:
  - cat argosTrack.Rcheck/00check.log
  - cat argosTrack.Rcheck/00install.out
